export const dataProps = [
	{ class: 'elevation-0' },
	{ class: 'elevation-1' },
	{ class: 'elevation-2' },
	{ class: 'elevation-3' },
	{ class: 'elevation-4' },
	{ class: 'elevation-5' },
	{ class: 'elevation-6' },
	{ class: 'elevation-7' },
	{ class: 'elevation-8' },
	{ class: 'elevation-9' },
	{ class: 'elevation-10' },
	{ class: 'elevation-11' },
	{ class: 'elevation-12' },
	{ class: 'elevation-13' },
	{ class: 'elevation-14' },
	{ class: 'elevation-15' },
	{ class: 'elevation-16' },
	{ class: 'elevation-17' },
	{ class: 'elevation-18' },
	{ class: 'elevation-19' },
	{ class: 'elevation-20' },
	{ class: 'elevation-21' },
	{ class: 'elevation-22' },
	{ class: 'elevation-23' },
	{ class: 'elevation-24' }
];
